services:
  app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/gl_erp
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: gl-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gl_erp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:

